var flashItems = [
  {
    aboutImage: "CSS & HTML ice-cream shop",
    seeMore: "See More",
    image: "images/card1.jpg",
    link: "https://codepen.io/kemiowoyele1/pen/KKVVvbN",
  },
  {
    aboutImage: "CSS & HTML Christmas Card",
    seeMore: "See More",
    image: "images/card2.jpg",
    link: "https://codepen.io/kemiowoyele1/pen/QWqaLNz",
  },
  {
    aboutImage: "CSS & HTML Sallah Greeting",
    seeMore: "See More",
    image: "images/card3.jpg",
    link: "https://codepen.io/kemiowoyele1/pen/rNObBav",
  },
  {
    aboutImage: "Baby First Words Learning App",
    seeMore: "See More",
    image: "images/happy-balloons.png",
    link: "happy-balloons/index.html",
  },
  {
    aboutImage: "CSS & HTML Birthday Cake",
    seeMore: "See More",
    image: "images/card4.jpg",
    link: "https://codepen.io/kemiowoyele1/pen/KKVZvQY",
  },
  {
    aboutImage: "CSS & HTML Space Ship",
    seeMore: "See More",
    image: "images/card5.jpg",
    link: "https://codepen.io/kemiowoyele1/pen/KKWNdMo",
  },
  {
    aboutImage: "CSS & HTML crying girl",
    seeMore: "See More",
    image: "images/card6.jpg",
    link: "https://codepen.io/kemiowoyele1/pen/xxZxrmy",
  },
  // {
  //     "aboutImage": "baby phone chat page (Mobile App)",
  //     "seeMore": "Download App",
  //     "image": "images/card7.jpg",
  //     "link": "#"
  // },
  // {
  //     "aboutImage": "baby phone, video call page ",
  //     "seeMore": "Download App",
  //     "image": "images/card8.jpg",
  //     "link": "#"
  // },
  // {
  //     "aboutImage": "baby piano, animal sounds page ",
  //     "seeMore": "Download App",
  //     "image": "images/card9.jpg",
  //     "link": "#"
  // },
  // {
  //     "aboutImage": "baby piano, quiz selection page ",
  //     "seeMore": "Download App",
  //     "image": "images/card10.jpg",
  //     "link": "#"
  // },
  // {
  //     "aboutImage": "baby piano, alphabet and numbers flash card page ",
  //     "seeMore": "Download App",
  //     "image": "images/card11.jpg",
  //     "link": "#"
  // },
  {
    aboutImage: "my baby laptop, home page ",
    seeMore: "Download App",
    image: "images/card12.jpg",
    link: "#",
  },
  // {
  //     "aboutImage": "my baby phone, fan page ",
  //     "seeMore": "Download App",
  //     "image": "images/card13.jpg",
  //     "link": "#"
  // },
  // {
  //     "aboutImage": "my baby piano, home page ",
  //     "seeMore": "Download App",
  //     "image": "images/card14.jpg",
  //     "link": "#"
  // },
  {
    aboutImage: "my baby music phone, home page ",
    seeMore: "Download App",
    image: "images/card15.jpg",
    link: "#",
  },
  {
    aboutImage: "my baby music phone, call page ",
    seeMore: "Download App",
    image: "images/card16.jpg",
    link: "#",
  },
  {
    aboutImage: "my baby music phone, piano page ",
    seeMore: "Download App",
    image: "images/card17.jpg",
    link: "#",
  },
  {
    aboutImage: "my baby music phone, animal sounds page ",
    seeMore: "Download App",
    image: "images/card18.jpg",
    link: "#",
  },
  {
    aboutImage: "my baby music phone, airplane page ",
    seeMore: "Download App",
    image: "images/card19.jpg",
    link: "#",
  },
  {
    aboutImage: "my baby music phone, call page ",
    seeMore: "Download App",
    image: "images/card20.jpg",
    link: "#",
  },
  {
    aboutImage: "my baby music phone, singing penguin ",
    seeMore: "Download App",
    image: "images/card21.jpg",
    link: "#",
  },
  {
    aboutImage: "bouncing balls",
    seeMore: "view page",
    image: "images/bounce.png",
    link: "pages/bouncinghead.html",
  },
  {
    aboutImage: " Hue Sliding Button ",
    seeMore: "view page",
    image: "images/slide.png",
    link: "pages/button9.html",
  },
  {
    aboutImage: "divs with random colors",
    image: "images/divs.png",
    link: "pages/createDivs.html",
  },
  {
    aboutImage: "Cat with animated ears",
    seeMore: "view page",
    image: "images/css-cat.png",
    link: "pages/cute-cat.html",
  },
  {
    aboutImage: "music player with vue js",
    seeMore: "See More",
    image: "images/music-player.png",
    link: "https://music-player-with-vuejs.netlify.app/#/",
  },
  {
    aboutImage: "School Project",
    seeMore: "See More",
    image: "images/edu.jpg",
    link: "https://edupower6.netlify.app/",
  },
  {
    aboutImage: "covid Project",
    seeMore: "See More",
    image: "images/covid.png",
    link: "https://tiidelab-stop-covid.netlify.app/",
  },
  {
    aboutImage: "covid Project",
    seeMore: "See More",
    image: "images/covid.png",
    link: "https://covid-19-real-info.netlify.app/",
  },
  {
    aboutImage: "covid Project",
    seeMore: "See More",
    image: "images/covid.png",
    link: "https://covid-19-real-info.netlify.app/",
  },
  {
    aboutImage: "CSS Moving train",
    seeMore: "See More",
    image: "images/card27.jpg",
    link: "https://css-moving-train.netlify.app/",
  },
  {
    aboutImage: "Simple interest calculator",
    seeMore: "See More",
    image: "images/simple.png",
    link: "https://vuesimpleinterest.netlify.app/",
  },
  {
    aboutImage: "CSS Car",
    seeMore: "See More",
    image: "images/CSScar.png",
    link: "https://css-rolling-car.netlify.app/",
  },
  {
    aboutImage: "Vue JS Music Player",
    seeMore: "See More",
    image: "images/vue-music.png",
    link: "https://musicplayer1111.netlify.app/#/",
  },
  {
    aboutImage: "Compound Interest Calculator",
    seeMore: "See More",
    image: "images/compound.png",
    link: "https://vue-compound-interest123.netlify.app/",
  },
  {
    aboutImage: "Vue JS E-commerce Frontend",
    seeMore: "See More",
    image: "images/gele.JPG",
    link: "https://chrismartvue.netlify.app/",
  },

  {
    aboutImage: "Church Website",
    seeMore: "See More",
    image: "images/church.png",
    link: "https://christ-resurrection-and-salvation.netlify.app/",
  },
  {
    aboutImage: "Multiplication Table App",
    seeMore: "See More",
    image: "images/shuttle.png",
    link: "https://2times-table.netlify.app/",
  },
  {
    aboutImage: "javaScript fireworks",
    seeMore: "See More",
    image: "images/fire.png",
    link: "fireworks/firew.html",
  },
  {
    aboutImage: "Bubble Popping Game",
    seeMore: "See More",
    image: "images/bubbles.png",
    link: "happy-bubbles/index.html",
  },
  {
    aboutImage: "Honey Hunting Desktop/pc Game",
    seeMore: "See More",
    image: "images/honey.png",
    link: "finder/index.html",
  },
  {
    aboutImage: "javaScript Fireworks",
    seeMore: "See More",
    image: "images/fireworks.png",
    link: "fireworks/firew.html",
  },
  {
    aboutImage: "Local Storage Todo List app",
    seeMore: "See More",
    image: "images/ls.png",
    link: "local-storage/index.html",
  },
  {
    aboutImage: "HTML & CSS Funny Face",
    seeMore: "See More",
    image: "images/face.png",
    link: "pages/grace.html",
  },
  {
    aboutImage: "HTML & CSS Alien Face",
    seeMore: "See More",
    image: "images/alien.png",
    link: "pages/green-alian.html",
  },
  {
    aboutImage: "HTML & CSS Humpty Dumpties",
    seeMore: "See More",
    image: "images/humpty.png",
    link: "pages/hupty.html",
  },

  {
    aboutImage: "HTML & CSS and JS spinner",
    seeMore: "See More",
    image: "images/spin.png",
    link: "pages/newSpin.html",
  },

  {
    aboutImage: "scroll effect",
    seeMore: "See More",
    image: "images/scroll.png",
    link: "pages/scrolleffect2.html",
  },
  {
    aboutImage: "space ship demo for wrong quiz answer",
    seeMore: "See More",
    image: "images/space1.png",
    link: "pages/spaceship-fail.html",
  },

  {
    aboutImage: "space ship demo for correct quiz answer",
    seeMore: "See More",
    image: "images/space2.png",
    link: "pages/spaceship.html",
  },
  {
    aboutImage: "HTML & CSS and JS spinner",
    seeMore: "See More",
    image: "images/spin2.png",
    link: "pages/spin.html",
  },

  {
    aboutImage: "HTML & CSS theatre",
    seeMore: "See More",
    image: "images/theatre.png",
    link: "pages/theatre.html",
  },
  {
    aboutImage: "HTML & CSS receipt app",
    seeMore: "See More",
    image: "images/cart.png",
    link: "pages/sumcart.html",
  },
  {
    aboutImage: "HTML & CSS 2d to 3d transform card",
    seeMore: "See More",
    image: "images/cart.png",
    link: "css-tricks/2d-3d-css-layered-card.html",
  },
  {
    aboutImage: "HTML & CSS magic show advert",
    seeMore: "See More",
    image: "images/cart.png",
    link: "css-tricks/magic-stage/magic-show-ad.html",
  },
  {
    aboutImage: "HTML & CSS head ball juggling performance",
    seeMore: "See More",
    image: "images/cart.png",
    link: "css-tricks/magic-stage/magic-stage-copy.html",
  },
  {
    aboutImage: "HTML & CSS magician ball juggling performance",
    seeMore: "See More",
    image: "images/cart.png",
    link: "css-tricks/magic-stage/magic-stage.html",
  },
  {
    aboutImage: "HTML & CSS head ball juggling performance",
    seeMore: "See More",
    image: "images/cart.png",
    link: "css-tricks/magic-stage/new-stage1.html",
  },
  {
    aboutImage: "HTML & CSS Magic Show Advert: new stage",
    seeMore: "See More",
    image: "images/cart.png",
    link: "css-tricks/magic-stage/new-stage1.html",
  },
  {
    aboutImage: "HTML & CSS Magic 3d Book",
    seeMore: "See More",
    image: "images/3dbook.png",
    link: "css-tricks/3dbook.html",
  },
  {
    aboutImage: "HTML & CSS Magic 3d check gradient wall",
    seeMore: "See More",
    image: "images/check.png",
    link: "css-tricks/check.html",
  },
  {
    aboutImage: "HTML & CSS Magic 3d rotating octahedron",
    seeMore: "See More",
    image: "images/octahedron.png",
    link: "css-tricks/3d-rotating-octahedron-image-gallery.html",
  },
  {
    aboutImage: "HTML & CSS Magic 3d illustration",
    seeMore: "See More",
    image: "images/3d.png",
    link: "css-tricks/3d.html",
  },
  {
    aboutImage: "HTML & CSS Magic 3d gallery slides",
    seeMore: "See More",
    image: "images/3d-slides.png",
    link: "css-tricks/3dslides.html",
  },
  {
    aboutImage: "HTML & CSS Magic animated colorful rain",
    seeMore: "See More",
    image: "images/color-rain.png",
    link: "css-tricks/animated-colorful-rain-effect.html",
  },
  {
    aboutImage: "HTML & CSS Magic Check Box",
    seeMore: "See More",
    image: "images/checkbox.png",
    link: "css-tricks/check-box.html",
  },
  {
    aboutImage: "HTML & CSS 3dCheck Box",
    seeMore: "See More",
    image: "images/checkbox2.png",
    link: "css-tricks/checkbox2.html",
  },
  {
    aboutImage: "HTML & CSS Magic Check Box",
    seeMore: "See More",
    image: "images/checkbox3.png",
    link: "css-tricks/checkbox3.html",
  },
  {
    aboutImage: "HTML & CSS and Js raining stars",
    seeMore: "See More",
    image: "images/star-rain.png",
    link: "css-tricks/confetti-effect.html",
  },
  {
    aboutImage: "HTML & CSS Easter Greeting With SVG Filters",
    seeMore: "See More",
    image: "images/easter.png",
    link: "css-tricks/easter-greeting.html",
  },
  {
    aboutImage: "HTML & CSS Text on Fire with SVG filters",
    seeMore: "See More",
    image: "images/fire-text.png",
    link: "css-tricks/fire-text-animation-effect.html",
  },
  {
    aboutImage: "HTML & CSS flame of Fire with SVG filters",
    seeMore: "See More",
    image: "images/fire-flame.png",
    link: "css-tricks/flame-of-fire.html",
  },
  {
    aboutImage: "HTML & CSS Paper Fold",
    seeMore: "See More",
    image: "images/fold.png",
    link: "css-tricks/folded-paper.html",
  },
  {
    aboutImage: "HTML & CSS Coding Magic Hat and Wand",
    seeMore: "See More",
    image: "images/hat.png",
    link: "css-tricks/follow-page-ad.html",
  },
  {
    aboutImage: "HTML, CSS & JS fun effect",
    seeMore: "See More",
    image: "images/fun.png",
    link: "css-tricks/fun-effect.html",
  },
  {
    aboutImage: "HTML & CSS gradient Text effect",
    seeMore: "See More",
    image: "images/text.png",
    link: "css-tricks/gradient-text-stroke-effect.html",
  },
  {
    aboutImage: "HTML, CSS & JS heart animation on mouse move",
    seeMore: "See More",
    image: "images/heart.png",
    link: "css-tricks/heart-animation-on-mouse-move.html",
  },
  {
    aboutImage: "HTML, CSS & JS animate siblings on hover",
    seeMore: "See More",
    image: "images/siblings.png",
    link: "css-tricks/hover-to-affect-siblings.html",
  },
  {
    aboutImage: "HTML, CSS & JS image step by step animation",
    seeMore: "See More",
    image: "images/steps.png",
    link: "css-tricks/image-magic-animation.html",
  },
  {
    aboutImage: "HTML, CSS & JS image step by step animation from top",
    seeMore: "See More",
    image: "images/steps2.png",
    link: "css-tricks/image-span-animation.html",
  },
  {
    aboutImage: "HTML, CSS & JS image pixel animation effect",
    seeMore: "See More",
    image: "images/pixel.png",
    link: "css-tricks/pixel-animation-effect.html",
  },
  {
    aboutImage: "HTML, CSS & JS image pixel animation from top",
    seeMore: "See More",
    image: "images/pixel2.png",
    link: "css-tricks/pixel-animation-falling-effect.html",
  },
  {
    aboutImage: "HTML & CSS Halloween Art",
    seeMore: "See More",
    image: "images/pumpkin.png",
    link: "css-tricks/pumpkin.html",
  },
  {
    aboutImage: "HTML & CSS 3d rotating phyramid",
    seeMore: "See More",
    image: "images/phyramid.png",
    link: "css-tricks/pyramid.html",
  },
  {
    aboutImage: "HTML & CSS Sallah greeting card",
    seeMore: "See More",
    image: "images/sallah.png",
    link: "css-tricks/sallah-ram.html",
  },
  {
    aboutImage: "HTML & CSS 3d sphere",
    seeMore: "See More",
    image: "images/sphere.png",
    link: "css-tricks/sphere.html",
  },
  {
    aboutImage: "HTML, CSS and Js animate star on mouse move",
    seeMore: "See More",
    image: "images/star.png",
    link: "css-tricks/star-animation-effect.html",
  },
  {
    aboutImage: "HTML, CSS Magic Wands and Magician Hat",
    seeMore: "See More",
    image: "images/wand.png",
    link: "css-tricks/wand-hat.html",
  },
  {
    aboutImage: "HTML, CSS water drop card effect",
    seeMore: "See More",
    image: "images/water1.png",
    link: "css-tricks/water-drop-card-effect.html",
  },
  {
    aboutImage: "HTML, CSS water drop card effect",
    seeMore: "See More",
    image: "images/water1.png",
    link: "css-tricks/water-drop-card-effect.html",
  },
];
console.log(flashItems.length);
